version: "3"

services:
  backend:
    container_name: kpd-backend
    build: ./backend
    image: backend-image
    env_file: ./backend/.env
    restart: always
    ports:
      - "4000:4200"
    networks:
      - db_network
      - frontend_network
    depends_on:
      - database

  frontend:
    container_name: kpd-frontend
    build: ./frontend
    image: frontend-image
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    networks:
      - frontend_network

  database:
    container_name: pg-database
    image: postgres:14-alpine
    env_file: ./backend/.env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - db_network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - db_network
    depends_on:
      - database

volumes:
  postgres_data:

networks:
  db_network:
  frontend_network:
